# Generated by Django 4.0.5 on 2022-07-02 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hitbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leaderboardy',
            new_name='Leaderboard',
        ),
    ]
